// Pawn
const RADIUS = 10
const MOVEMENT_SPEED = 2

// Game
const GAME_SPEED_RATE = 16.67

// Network
const INTERPOLATION_OFFSET = 1000

export { RADIUS, MOVEMENT_SPEED, GAME_SPEED_RATE, INTERPOLATION_OFFSET }
